version: '3.8'

services:
  presidio-analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    environment:
      - PRESIDIO_ANALYZER_DEFAULT_LANGUAGE=fr
      - PYTHONPATH=/usr/bin/presidio-analyzer:/app
      - GUNICORN_CMD_ARGS="--log-level debug --error-logfile - --access-logfile - --capture-output"
      - PYTHONUNBUFFERED=1
    command: ["gunicorn", "--bind", "0.0.0.0:3000", "--workers", "1", "--log-level", "debug", "--timeout", "120", "presidio_analyzer.app:app"]


  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    container_name: presidio-anonymizer
    restart: unless-stopped
    ports:
      - "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
